export interface ICreateCostumer
{
    name: string,
    email: string,
    cpf: string,
    sexo: string,
    profissao: string,
    endereco: string,
    telefone: string,
    telefoneEmergencia: string,
    dataNasc: Date,
    tratamentoAnterior: string,
    toxinaBotulinica: string,
    toxinaBotulinica_regiao: string,
    toxinaBotulinica_produto: string,
    fioSustentacao: string,
    fioSustentacao_regiao: string,
    fioSustentacao_produto: string,
    liftCirurgico: string,
    liftCirurgico_regiao: string,
    liftCirurgico_produto: string,
    peelingQuimico: string,
    peelingQuimico_regiao: string,
    peelingQuimico_produto: string,
    laser: string,
    laser_regiao: string,
    laser_produto: string,
    usaMedicamento: string,
    usaMedicamento_qual: string,
    trabalhoExpostoCalor: string,
    alergia: string,
    gestante_lactante: string,
    intoleranciaLactose: string,
    diabetes: string,
    roacutam: string,
    obs: string,
    tratamento: string
}